site_name: 'Compose Date Time Picker'
site_description: 'Jetpack Compose Date Time Picker'
site_author: 'Pranav Maganti'
site_url: 'https://qawaz.github.io/compose-datetime/'
remote_branch: gh-pages

docs_dir: docs

repo_name: 'compose-datetime'
repo_url: 'https://github.com/Qawaz/compose-datetime'

nav:
  - 'Overview': index.md
  - 'DateTime':
    - 'Guide': DateTimePicker.md
    - 'API': api/datetime

theme:
  name: material
  palette:
    - deep purple: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode